### ISSUE TITLE
[Feature Request]: Migrate the old MintDaoProposal to daospace 

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin-framework#101]
# Feature Request

**Describe the Feature Request**

Migrate the old MintDaoProposal to daospace

Usecase:

1. Delegate a Token mint capability to DAO.
2. Mint Token via DAO Proposal.

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by 0xpause** [comment]
working

**Comment by jolestar** [comment]
> 这个是不是需要支持任意的，多个不同的 Token 类型的 mint 能力？

对，相当于以 DAO 的身份发行 Token
