### ISSUE TITLE
[Feature Request]: Migrate the old OnChainConfigDao to daospace 

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin-framework#102]
# Feature Request

**Describe the Feature Request**

Migrate the old OnChainConfigDao to daospace

1. Implement the new OnChainConfig Proposal plugin for daospace
2. Move `Config::ModifyConfigCapability<ConfigT>` to daospace 

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by 0xpause** [comment]
Is this feature  already completed in https://github.com/starcoinorg/starcoin-framework/blob/main/sources/daospaceplugin/ConfigProposalPlugin.move ?

**Comment by jolestar** [comment]
> Is this feature already completed in https://github.com/starcoinorg/starcoin-framework/blob/main/sources/daospaceplugin/ConfigProposalPlugin.move ?

Yes. just need to review.
