### ISSUE TITLE
Logic issue in SalaryGovPlugin

### ISSUE THREAD

**Issue by 0xpause** [starcoinorg/starcoin-framework#104]
# Feature Request

**Describe the Feature Request**

For now,  signer with boss_cap can [set_salary_period](https://github.com/starcoinorg/starcoin-framework/blob/70429e2bee0cbd2f3cf59dadc94936d36c868615/sources/daospaceplugin/SalaryGovPlugin.move#L40) without limit, that's in fact a way to modify the salary for all member. It's not reasonable and fair for members.

**Describe Preferred Solution**

Give every member an independent `period` config
the period can be:
- option 1: unmodifiable
- option 2: modified when both boss and member confirmed.

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by 0xpause** [comment]
I'm trying to fix this and add integration test, but found a more serious issue, that is: every member's SBT amount is 0, and there's no boss in the initial state, and the boss can only be selected through proposal but no one has vote weights. It's deadlock!

So I want to know which scenario will this plugin be used for and try to find a feasible solutions. @jolestar @WGB5445 @baichuan3 @welbon

**Comment by jolestar** [comment]
I think the salary and boss system are too complex to adapt to different DAO, and we should move the SalaryGovPlugin as a test plugin; 

maybe it can be a third-part plugin not in Framework.
