### ISSUE TITLE
[Code]: Unify entry function

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin-framework#109]
Unify entry(script) function for new Modules after v11:

1. Provide a `public fun xxx(sender:&signer .. ` function accept `&signer` for another module call.
2. Provide a `public(script) fun xxx_entry(sender: signer..` function accept `signer` as entry function.

**Comment by jolestar** [comment]
cc @0xpause @WGB5445

**Comment by 0xpause** [comment]
Get it !
