### ISSUE TITLE
[Code]: StakeToSBTPlugin: no SBT decreased when unstake

### ISSUE THREAD

**Issue by 0xpause** [starcoinorg/starcoin-framework#113]
In StakeToSBTPlugin.move, no SBT decreased when unstake token [here](https://github.com/starcoinorg/starcoin-framework/blob/7a38b4b8b99f6d61eaa5e38479ad0b1ab2292bc4/sources/daospaceplugin/StakeToSBTPlugin.move#L179) and [here](https://github.com/starcoinorg/starcoin-framework/blob/7a38b4b8b99f6d61eaa5e38479ad0b1ab2292bc4/sources/daospaceplugin/StakeToSBTPlugin.move#L164).

It's a feature or bug ? 
@jolestar @WGB5445 @welbon @baichuan3

**Comment by jolestar** [comment]
SBT is a reward for staking tokens for a period. So do not need to decrease SBT when unstake.

**Comment by 0xpause** [comment]
Get it.
