### ISSUE TITLE
[Code]:  Not suitable to use default weight when state in StakeToSBTPlugin.move

### ISSUE THREAD

**Issue by 0xpause** [starcoinorg/starcoin-framework#114]
In [StakeToSBTPlugin::stake](https://github.com/starcoinorg/starcoin-framework/blob/7a38b4b8b99f6d61eaa5e38479ad0b1ab2292bc4/sources/daospaceplugin/StakeToSBTPlugin.move#L113), default weight is used when `lock_time` is not matched with any config. Is that designed?

I think the default weight may not be suitable here, the may be two situations:

1. It may cover mistakes and not in line with user expectations, especially when user stake a large amount of token with a long `lock_time` by mistake or bug of  the DAO. User may never get they token back.
2. User can hack the system to get SBT by stake in very short `lock_time` , 1 second for example.

I think ABORT is ok when the input `lock_time` is not matched with any config.

**Comment by welbon** [comment]
The PR for this enhancement has been created in https://github.com/starcoinorg/starcoin-framework/pull/117
