### ISSUE TITLE
[Feature Request]: check the proposal state and do deposit or burn

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin-framework#119]
# Feature Request

**Describe the Feature Request**

https://github.com/starcoinorg/starcoin-framework/blob/08928d4db8c2603f6433476697d0fddd0aa759bd/sources/daospace/DAOSpace.move#L1674-L1677

if the proposal state is `no_with_veto`, we should burn the deposit Token.

Ensure the `no_with_veto` work as expected.

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by WGB5445** [comment]
https://github.com/starcoinorg/starcoin-framework/blob/08928d4db8c2603f6433476697d0fddd0aa759bd/sources/daospace/DAOSpace.move#L1639
在这里确定了只有 `EXECUTABLE` 的提案才能被执行提案，但当 `no_with_veto` 后，应添加状态为 `DEFEATED` 提案处理，并增加 状态为 `DEFEATED` 的提案 `Burn Token` 

需要的改动：
1. 增加 `DEFEATED` 提案处理
2. 修改 `take_proposal_action`函数，增加 `burn Token`
