### ISSUE TITLE
[Feature Request]: DAOSpace Use Offer for Member and Grant

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin-framework#125]
# Feature Request

**Describe the Feature Request**

当前如果要邀请用户加入 DAO，投票通过后，用户无法直接加入，该用户必须先 `Accept` 成员 NFT, 然后才能加入。给用户发 Grant 也有类似的问题。

是否考虑提供 Offer 机制，先将 NFT 或者 Grant 放在 Offer 里，存在 DAO 账户下，然后用户自己来领取？不过这个也涉及 Offer module 的重构，需要将 Offer 改造成数组，这样才能保存多个。

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by jolestar** [comment]
@WGB5445 @0xpause

**Comment by 0xpause** [comment]
从 Offer 里取是不是也要用户先 Accept 操作？

**Comment by jolestar** [comment]
> 从 Offer 里取是不是也要用户先 Accept 操作？

Offer 是保存在 DAO 账户下的，用户来取的时候就顺便 accept 了，不需要预先 accept。

**Comment by WGB5445** [comment]
这个我来搞吧，增加一个 `offer_v2`

**Comment by jolestar** [comment]
> 这个我来搞吧，增加一个 `offer_v2`

或者弄成自动化的，如果只有一个 offer 就直接存，存第二个的时候变成数组。

**Comment by 0xpause** [comment]
#174 已经解决，关闭该 issue。
