### ISSUE TITLE
[Feature Request] Account::deposit(address, token) should auto create account 

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin-framework#13]
# Feature Request

**Describe the Feature Request**

if We call `Account::deposit(address, token)` in a module, and the account of address do not exist, will raise an error with code: 27141

```
{
    "category_code": 5,
    "category_name": "NOT_PUBLISHED",
    "reason_code": 106,
    "reason_name": "ERR_TOKEN_NOT_ACCEPT"
  }
```

The account creates at the script:

```
    public(script) fun peer_to_peer_v2<TokenType: store>(account: signer, payee: address, amount: u128) {
        if (!Account::exists_at(payee)) {
            Account::create_account_with_address<TokenType>(payee);
        };
        Account::pay_from<TokenType>(&account, payee, amount)
    }
```

**Describe Preferred Solution**

Auto-create the account if the account does not exist when call `Account::deposit`

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by WGB5445** [comment]
I can try to get it done
