### ISSUE TITLE
[Code]:  Migrate test_modify_on_chain_config_reward_by_dao test to starcoin-framework integration-test

### ISSUE THREAD

**Issue by 0xpause** [starcoinorg/starcoin-framework#137]
[test_modify_on_chain_config_reward_by_dao](https://github.com/starcoinorg/starcoin/blob/0a252790288b70f76ad6a22a35a1ea6962901da8/chain/tests/test_epoch_switch.rs#L383)

**Comment by WGB5445** [comment]
#112 里面已经包括了 ` on_chain_config_reward_by_dao` ，他应该是 `StarcoinDAO` 的一部分https://github.com/starcoinorg/starcoin-framework/blob/main/integration-tests/starcoin_dao/starcoin_onchain_config.move#L73-L81

**Comment by 0xpause** [comment]
OK
