### ISSUE TITLE
[Code]:  DAOSpace GlobalProposals not removed after being executed or rejected.

### ISSUE THREAD

**Issue by 0xpause** [starcoinorg/starcoin-framework#143]
[GlobalProposals](https://github.com/starcoinorg/starcoin-framework/blob/e82c1d32c98170e82f2145bf5a03badf8af06de7/sources/daospace/DAOSpace.move#L1291) is never removed after being executed or rejected. 

The vector is always growing, there may have state explosion issue.

**Comment by jolestar** [comment]
also, need to add max limit to GlobalProposals

https://github.com/starcoinorg/starcoin-framework/blob/e82c1d32c98170e82f2145bf5a03badf8af06de7/sources/daospace/DAOSpace.move#L1467-L1470

**Comment by 0xpause** [comment]
Delete proposal after executed or rejected? Is there a need to keep them for querying history proposal info?

**Comment by jolestar** [comment]
> Delete proposal after executed or rejected directly. Is there a need to keep them for querying history proposal info?

I think they can bean deleted. The history proposal can query from history state or off-chain index DB.

**Comment by 0xpause** [comment]
ok, I will fix it.
