### ISSUE TITLE
[Code]: Proposals of the same type with different values exist at the same time

### ISSUE THREAD

**Issue by 0xOutOfGas** [starcoinorg/starcoin-framework#157]
**Framework Version：** v11
**Description**: We found that more than oneModifyDaoConfigProposal can exist at the same time. If they have different values, and all pass, what is the right behavior? Suppose there are two different ModifyDaoConfigProposal, A and B. Some users support A, and some users support B. After the final update of ModifyDaoConfigProposa, if the users supporting A see the result as B, it's confusing. The same problem may exist for OnChainConfigScript and UpgradeModuleDaoProposal.
```
// setup two ModifyDaoConfigProposal at the same time
account unlock 0x4245dd5c48ebf53f8728748d6276636b
account execute-function -s 0x4245dd5c48ebf53f8728748d6276636b --function 0x1::ModifyDaoConfigProposal::propose -t 0x1::STC::STC --arg 60000 --arg 600000 --arg 4u8 --arg 1000 --arg 0

account unlock -p "" 0xc4e7ce4f9f5983b802cb819f900c567f
account execute-function -s 0xc4e7ce4f9f5983b802cb819f900c567f --function 0x1::ModifyDaoConfigProposal::propose -t 0x1::STC::STC --arg 60000 --arg 700000 --arg 4u8 --arg 1000 --arg 0
```
**Recommendation**: Supporting only one proposal for the same type at the same time.

**Comment by jolestar** [comment]
Resolved in the new DAOSpace.
