### ISSUE TITLE
bug: Newly created DAOs cannot initiate proposals due to no initial members

### ISSUE THREAD

**Issue by yubing744** [starcoinorg/starcoin-framework#159]
# Bug Report

branch: master
commit: d2c4f5c28d97dbe856fcbc4bf0a39bb4bfa362b1

**Current behavior:**

When I created the DAO, I did not have the ability to specify initial members. After the DAO was created successfully, no one could initiate a proposal to add new members.

**Expected behavior:**

DAOSpace provides methods to add members based on root_cap

**Comment by yubing744** [comment]
@jolestar

**Comment by WGB5445** [comment]
It may be necessary to register DAOT as a member plugin when creating DAO
and add the caller as the first DAO member

**Comment by jolestar** [comment]
first member need to init in the template

**Comment by yubing744** [comment]
how about add script function join_member_with_root_cap in DAOSpace?

**Comment by yubing744** [comment]
This is DAO create tempate  in starcoin-dao-frontend:

https://github.com/starcoinorg/starcoin-dao-frontend/blob/51de903045d9c9fbd6839ffaf4a6474a290c9d96/src/contracts/template/DAO/sources/MyDAO.move.js#L58-L86

**Comment by yubing744** [comment]
The current logical caller account will be upgraded to DAO, is it possible to create a new account here for DAO creation

**Comment by WGB5445** [comment]
In the previous logic, you can use ${daoName} as a plugin to apply for member_cap permission to make an account a member

**Comment by WGB5445** [comment]
There is no way to specify other accounts as members when the account is upgraded. Here is a solution. Member can be issued through the Offer mechanism, and a member Offer can be issued to an address when it is created.

**Comment by yubing744** [comment]
Like this:

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/1449069/192466973-9746b244-540f-472c-9fdf-735071dce976.png">

**Comment by yubing744** [comment]
After changing from DAOAccount::upgrade_to_dao to DAOAccount::create_account, creating DAO reports an error:

ALERT: Starmask: contract.dry_run_raw failed. Error: {"MoveAbort":{"abort_code":25858,"explain":{"category_code":2,"category_name":"REQUIRES_ADDRESS","reason_code":101,"reason_name ":"ETOKEN_REGISTER"},"location":{"Module":{"address":"0x00000000000000000000000000000001","name":"Token"}}}}

**Comment by jolestar** [comment]
> Like this:
> 
> <img alt="image" width="1167" src="https://user-images.githubusercontent.com/1449069/192466973-9746b244-540f-472c-9fdf-735071dce976.png">

1. if upgrade the sender to DAO account, need to use another account as the first member.
2. if the sender creates a new DAO account, the sender can be the first member.

I think in the DAOSpace web scenario, 2 is the right approach.

**Comment by yubing744** [comment]
@jolestar 2 will Abort, when create Token in DAOSpace::create_dao, the error is:  {"MoveAbort":{"abort_code":25858,"explain":{"category_code":2,"category_name":"REQUIRES_ADDRESS","reason_code":101,"reason_name ":"ETOKEN_REGISTER"},"location":{"Module":{"address":"0x00000000000000000000000000000001","name":"Token"}}}}

**Comment by jolestar** [comment]
> After changing from DAOAccount::upgrade_to_dao to DAOAccount::create_account, creating DAO reports an error:
> 
> ALERT: Starmask: contract.dry_run_raw failed. Error: {"MoveAbort":{"abort_code":25858,"explain":{"category_code":2,"category_name":"REQUIRES_ADDRESS","reason_code":101,"reason_name ":"ETOKEN_REGISTER"},"location":{"Module":{"address":"0x00000000000000000000000000000001","name":"Token"}}}}

The right approach:

1. Alice creates a DAO account.
2. Alice builds a package with the DAOTemplate. The module address should be the DAO account address.
3. Alice submit an upgrade plan for DAOAccount.
4. Alice deploys the package to DAOAccount and initiates the DAO.

**Comment by yubing744** [comment]
> > After changing from DAOAccount::upgrade_to_dao to DAOAccount::create_account, creating DAO reports an error:
> > ALERT: Starmask: contract.dry_run_raw failed. Error: {"MoveAbort":{"abort_code":25858,"explain":{"category_code":2,"category_name":"REQUIRES_ADDRESS","reason_code":101,"reason_name ":"ETOKEN_REGISTER"},"location":{"Module":{"address":"0x00000000000000000000000000000001","name":"Token"}}}}
> 
> The right approach:
> 
> 1. Alice creates a DAO account.
> 2. Alice builds a package with the DAOTemplate. The module address should be the DAO account address.
> 3. Alice submit an upgrade plan for DAOAccount.
> 4. Alice deploys the package to DAOAccount and initiates the DAO.

It seems that this also requires DAOSpace to provide the join_member_with_root_cap method to add Alice as a member.

**Comment by yubing744** [comment]
@jolestar I found a new way to skip the upgrade plan:

1. Alice creates a DAO account, and holds DAOAccountCap
2. Alice builds a package with the DAOTemplate. The module address should be the DAO account address.
3. Alice deploys the package to DAOAccount and initiates the DAO with DAOAccountCap.

**Comment by jolestar** [comment]
> @jolestar I found a new way to skip the upgrade plan:
> 
> 1. Alice creates a DAO account, and holds DAOAccountCap
> 2. Alice builds a package with the DAOTemplate. The module address should be the DAO account address.
> 3. Alice deploys the package to DAOAccount and initiates the DAO with DAOAccountCap.

if there is no Upgrade Plan, Alice can not deploy the package to DAOAccount.

**Comment by yubing744** [comment]
> > @jolestar I found a new way to skip the upgrade plan:
> > 
> > 1. Alice creates a DAO account, and holds DAOAccountCap
> > 2. Alice builds a package with the DAOTemplate. The module address should be the DAO account address.
> > 3. Alice deploys the package to DAOAccount and initiates the DAO with DAOAccountCap.
> 
> if there is no Upgrade Plan, Alice can not deploy the package to DAOAccount.

I thought about it, it is true

**Comment by yubing744** [comment]
@jolestar How to deploy a Package to DAOAccount, is there a sample program?

**Comment by jolestar** [comment]
> @jolestar How to deploy a Package to DAOAccount, is there a sample program?

@0xpause can help to write an integration-test for give a example for this?

**Comment by 0xpause** [comment]
> > @jolestar How to deploy a Package to DAOAccount, is there a sample program?
> 
> @0xpause can help to write an integration-test for give a example for this?

I'll try to write one. For now,  you can have a look at the exampels [dao_proposal.move](https://github.com/starcoinorg/starcoin-framework/blob/main/integration-tests/daospace/dao_proposal.move) and [dao_upgrade.move](https://github.com/starcoinorg/starcoin-framework/blob/main/integration-tests/daospace/dao_upgrade.move)

**Comment by jolestar** [comment]
> > > @jolestar How to deploy a Package to DAOAccount, is there a sample program?
> > 
> > 
> > @0xpause can help to write an integration-test for give a example for this?
> 
> I'll try to write one. For now, you can have a look at the exampels [dao_proposal.move](https://github.com/starcoinorg/starcoin-framework/blob/main/integration-tests/daospace/dao_proposal.move) and [dao_upgrade.move](https://github.com/starcoinorg/starcoin-framework/blob/main/integration-tests/daospace/dao_upgrade.move). @yubing744

@WGB5445
