### ISSUE TITLE
[Feature Request]:  Add title and createdAt for DAOSpace proposal

### ISSUE THREAD

**Issue by yubing744** [starcoinorg/starcoin-framework#170]
# Feature Request

**Describe the Feature Request**

According to the previous proposal interface, proposals defined in DAOSpace now lack the proposal title and proposal creation time fields.

<img width="1447" alt="image" src="https://user-images.githubusercontent.com/1449069/193379423-496e490b-9d82-40b2-963f-7266ddad6a79.png">

**Comment by yubing744** [comment]
@jolestar @WGB5445

**Comment by jolestar** [comment]
I remember we discussed this. 

The `description` field is a to an IPFS json file and contains all the proposal's information.

**Comment by yubing744** [comment]
> description

Loading IPFS content on the list page will be slower because each list item is loaded. I think it is more appropriate to load IPFS content only on the details page.

**Comment by jolestar** [comment]
增加 title|description

扩展字段 properties ? 考虑使用什么方案

**Comment by 0xpause** [comment]
#183 已解决，关闭该 issue

**Comment by yubing744** [comment]
> #183 已解决，关闭该 issue

什么时候部署halley网络？

**Comment by WGB5445** [comment]
> > #183 已解决，关闭该 issue
> 
> 什么时候部署halley网络？

https://github.com/starcoinorg/starcoin/pull/3786
