### ISSUE TITLE
[Feature Request]: Let custom proposal's `quorum_votes`

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin-framework#177]
# Feature Request

**Describe the Feature Request**

当前，所有 Proposal 的 `quorum_votes` 都是通过 DAO 的配置计算出的，但实际场景下，DAO 的配置可能是一个基础的 quorum，而一些特殊的插件可能需要更高的 quorum，所以需要支持自定义 Proposal 的 quorum 设置。

支持方法：

1. 创建 Proposal 的时候提供一个参数，这个参数代表 quorum 的放大系数，默认为 1.
2. 一些特殊的插件，可以增加这个放大系数，在基础的 quorum 的基础上放大一个倍数.

案例：

1. TreasuryWithdrawProposal 投票通过的 quorum 应该高于从 DAO 的 balance 中提款的 Proposal.

思考：

是否支持缩小 quorum？考虑到安全问题，暂时可以不考虑允许缩小 quorum.

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by 0xpause** [comment]
我觉得使用 rate 的绝对值比较清晰。 默认配置 voting_quorum_rate 是 [0, 100] 范围的数值，表示占 supply 的比例。新增一个 参数 additional_voting_quorum_rate , 最终的 quorum_rate 为 voting_quorum_rate  + additional_voting_quorum_rate 。
