### ISSUE TITLE
bug: execute_token_accept_proposal_entry

### ISSUE THREAD

**Issue by wow-sven** [starcoinorg/starcoin-framework#206]
# Bug Report

**Starcoin Framework version:**

v12

**Current behavior:**

After the proposal vote is passed, call execute_token_accept_proposal_entry function report an error:

```
ALERT: Starmask: contract.dry_run_raw failed. 
Error: {
	"ExecutionFailure": {
		"code_offset": 1,
		"function": 0,
		"function_name": "emit_event",
		"location": {
			"Module": {
				"address": "0x00000000000000000000000000000001",
				"name": "EventUtil"
			}
		},
		"status": 4008,
		"status_code": "MISSING_DATA"
	}
}
```

**Expected behavior:**

Execute success

**Steps to reproduce:**

1、Call create_token_accept_proposal_entry
2、Vote pass
3、Call execute_token_accept_proposal_entry

**Other information:**

Network Barnard

**Comment by 0xpause** [comment]
The function StakeToSBTPlugin::install_event is public for everyone. You can call this too init the event resources once installed StakeToSBTPlugin.

**Comment by 0xpause** [comment]
> > The function StakeToSBTPlugin::install_event is public for everyone. You can call this too init the event resources once installed StakeToSBTPlugin.
> 
> Maybe we can call install_event in the StakeToSBTPlugin::install_plugin_proposal

What if the proposal fails?

**Comment by jolestar** [comment]
> > > The function StakeToSBTPlugin::install_event is public for everyone. You can call this too init the event resources once installed StakeToSBTPlugin.
> > 
> > 
> > Maybe we can call install_event in the StakeToSBTPlugin::install_plugin_proposal
> 
> What if the proposal fails?

We should call `install_event` in the `accept_token` function. And the `install_event` function should support re-entry because it may be called multi times.

https://github.com/starcoinorg/starcoin-framework/blob/94be70ef2fe528b4bf00e4623005588a600ea578/sources/daospaceplugin/StakeToSBTPlugin.move#L119-L122

**Comment by 0xpause** [comment]
@jolestar  You mean **shouldn't** call `install_event` in `accept_token` ?

**Comment by jolestar** [comment]
> @jolestar  You mean **shouldn't** call `install_event` in `accept_token` ?

In accept_token，not in accept_token_by_dao

**Comment by 0xpause** [comment]
Got it.
