### ISSUE TITLE
[Feature Request]:  Supports scheduled snapshot execution

### ISSUE THREAD

**Issue by yubing744** [starcoinorg/starcoin-framework#209]
# Feature Request

**Describe the Feature Request**

When performing voting, checkpoint is often forgotten, resulting in voting failure or invalidity

**Describe Preferred Solution**

Checkpoint calls the service regularly

**Describe Alternatives**

provides the contract method of create_proposal_with_checkpoint

**Related Code**

https://github.com/starcoinorg/starcoin-framework/blob/94be70ef2fe528b4bf00e4623005588a600ea578/sources/Block.move#L171-L173

**Comment by jolestar** [comment]
also need to execute `update_state_root_entry` after `checkpoint_entry`

https://github.com/starcoinorg/starcoin-framework/blob/94be70ef2fe528b4bf00e4623005588a600ea578/sources/Block.move#L247-L250

**Comment by wubuku** [comment]
Scheduled tasks are already running.
