### ISSUE TITLE
[Feature Request]: Implement WithdrawPlugin for DAOSpace

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin-framework#212]
# Feature Request

**Describe the Feature Request**

Implement WithdrawPlugin for DAOSpace, allowing withdrawal Token from DAOSpace balance by the proposal.

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by 0xpause** [comment]
功能上是否和 grant 有些重合？

**Comment by jolestar** [comment]
> 功能上是否和 grant 有些重合？

不，这个是直接提款。Grant 是有释放周期的。
