### ISSUE TITLE
[Feature Request]: Provide method to get block state root hash

### ISSUE THREAD

**Issue by muzixinly** [starcoinorg/starcoin-framework#39]
# Feature Request

**Describe the Feature Request**

There is a scene, in the on-chain snapshot voting, if the contract cannot obtain the state root hash of a certain block, it can only rely on the block height and state root hash passed in by the caller. The contract can only verify the proof, but cannot verify that the state root hash itself is valid.

**Comment by jolestar** [comment]
如果在不新增 native function 的前提下，有个可行的方案：

在 Block module 中提供一个 `checkpoint` 方法:

```

module Block{

struct Checkpoint has copy,drop,store{
   block_number: u64,
   block_hash: vector<u8>,
   state_root: Option<vector<u8>>,
}

struct Checkpoints has key{
   checkpoints: Vector<Checkpoint>,
}


public fun checkpoint(){
   let parent_block_number = current_block_number()-1;
   let parent_block_hash = parent_block_hash();
   //write checkpont to Checkpoints
   //检查 checkpoints 的长度，淘汰旧的数据
}

}

```

在 Block module 中提供一个 `latest_state_root()` 的 Move 方法

```
public fun latest_state_root():(u64,vector<u8>){
   //寻找最近的 state_root 不为空的 Checkpoint 返回
}
```

返回最近的 block number 以及对应的 state_root

同时提供一个更新 state root 的方法
```
public fun update_state_root(header:vector<u8>){
   let block_number = //从 header 中读取 block_number 字段
   let state_root = //从 header 中读取 state_root
   // 寻找 checkpoints 中的对应的 Checkpoint
   // 校验 header 的 hash 和 Checkpoint 中的一致
   // 更新 Checkpoint 中的 state_root 字段
}

```
