### ISSUE TITLE
[Feature Request]: Add event for DAOSpace::burn_root_cap

### ISSUE THREAD

**Issue by 0xpause** [starcoinorg/starcoin-framework#90]
# Feature Request

**Describe the Feature Request**

I think it's better to add an Event when burn root cap [DAOSpace::burn_root_cap](https://github.com/starcoinorg/starcoin-framework/blob/a981f67391256afe1c40ca90938c105b2981a29e/sources/daospace/DAOSpace.move#L326).

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by jolestar** [comment]
DAORootCap 不能 store，也不能 drop，只能 burn 掉。感觉是不是这个 event 没必要？

**Comment by 0xpause** [comment]
确实没有很大必要。
