### ISSUE TITLE
[Feature Request]:  After DAOSpace creates a DAO, it needs to provide the ability to modify the content in DAOExt

### ISSUE THREAD

**Issue by yubing744** [starcoinorg/starcoin-framework#99]
# Feature Request

**Describe the Feature Request**

After DAOSpace creates a DAO, it needs to provide the ability to modify the content in DAOExt

![image](https://user-images.githubusercontent.com/1449069/187472389-12fd2add-836a-4c6c-a736-6207a4b53a3b.png)

Custom DAO, after DAO is created through DAOSpace, the incoming DAOExt does not provide the ability to modify.

**Comment by 0xpause** [comment]
What capability should be needed to modify the DAOExt?

**Comment by yubing744** [comment]
DAOModifyExtCap

**Comment by 0xpause** [comment]
@yubing744 Added at #108
